apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"   
  name: test-cluster-autoscaler
  namespace: tks-system
  labels:
    executor: postman-executor
    test-type: postman-collection
spec:
  type: postman/collection
  content:
    repository:
      branch: master
      path: executors/postman/cluster-autoscaler/cluster-autoscaler.json
  source: testsource-tks-automated-tests
  executionRequest:
    jobTemplateReference: job-template-worker-system
    executePostRunScriptBeforeScraping: false