apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: test-spot-price-calculator
  namespace: tks-system
  labels:
    executor: postman-executor
    test-type: postman-collection
spec:
  type: postman/collection
  content:
    repository:
      branch: master
      path: executors/postman/spot-price-calculator/spot-price-calculator.json
  source: testsource-tks-automated-tests
  executionRequest:
    jobTemplateReference: job-template-worker-system
    executePostRunScriptBeforeScraping: false