apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: test-thanos
  namespace: tks-system
  labels:
    executor: postman-executor
    test-type: postman-collection
spec:
  type: postman/collection
  content:
    repository:
      branch: master
      path: executors/postman/thanos/thanos.json
  source: testsource-tks-automated-tests
  executionRequest:
    jobTemplateReference: job-template-worker-system
    executePostRunScriptBeforeScraping: false