apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"   
  name: test-vault-operator
  namespace: tks-system
  labels:
    executor: ginkgo-executor
    test-type: ginkgo-test
spec:
  type: ginkgo/test
  content:
    repository:
      branch: master
      path: executors/ginkgo/vault-operator
  source: testsource-tks-automated-tests
  executionRequest:
    jobTemplateReference: job-template-worker-system
    executePostRunScriptBeforeScraping: false