apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: check-prometheus
  namespace: testkube
  labels:
    app: prometheus
spec:
  type: curl/test
  content:
    type: git-file
    repository:
      type: git
      uri: https://github.com/cloud104/automated-tests.git
      branch: master
      path: executors/curl/prometheus/prometheus.json
      authType: basic
