apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-test
  namespace: default
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - totvscloud
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  commonName: '*.tstsoares10.staging.k8s.us-east-1.aws.tks.sh'
  dnsNames:
    - '*.tstsoares10.staging.k8s.us-east-1.aws.tks.sh'
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-dns-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
  secretName: cluster-ingress-wilcard-cert
