apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testkube
  name: testkube-test-deployment
  namespace: tks-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testkube
  template:
    metadata:
      labels:
        app: testkube
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: testkube
  name: testkube-test-svc
  namespace: tks-system
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: testkube
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testkube-test-ingress
  namespace: tks-system
spec:
  rules:
  - host: check-ingress.CLUSTERID.REGIONDNS
    http:
      paths:
      - backend:
          service:
            name: testkube-test-svc
            port:
              number: 80
        path: /
        pathType: Prefix

