apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault-test
  namespace: vault
spec:
  size: 1
  image: hashicorp/vault:1.15.1
  bankVaultsImage: ghcr.io/banzaicloud/bank-vaults:1.19.0
  # Specify the ServiceAccount where the Vault Pod and the Bank-Vaults configurer/unsealer is running
  serviceAccount: vault-test
  # A YAML representation of a final vault config file.
  # See https://www.vaultproject.io/docs/configuration/ for more information.
  config:
    storage:
      inmem: { }
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_disable: true
    ui: true
    log_level: debug
  # See: https://bank-vaults.dev/docs/cli-tool/#example-external-vault-configuration
  externalConfig:
    policies:
      - name: allow_secrets
        rules: |
          path "secret/*" {
            capabilities = ["create", "read", "update", "delete", "list"]
          }
    secrets:
      - path: secret
        type: kv
        description: General secrets.
        options:
          version: 2
    auth:
      - type: userpass
        users:
          - username: admin
            password: admin
            token_policies: allow_secrets
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: vault-test
  namespace: vault
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-test
  namespace: vault
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "*" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-test
  namespace: vault
roleRef:
  kind: Role
  name: vault-test
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: vault-test
