// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
)

// Injectors from injectors.go:

func SetUp(ctx context.Context, basename string) (*Test, func(), error) {
	test := &Test{}
	return test, func() {
	}, nil
}
