apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-node-local-dns-testkube-job
  namespace: tks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  argocd.argoproj.io/sync-wave: "-1"
  name: test-node-local-dns-clusterrolebinding-testkube-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-node-local-dns-clusterrole-testkube-job
subjects:
  - kind: ServiceAccount
    name: test-node-local-dns-testkube-job
    namespace: tks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  argocd.argoproj.io/sync-wave: "-1"
  name: test-node-local-dns-clusterrole-testkube-job
rules:
  - apiGroups: [ "apps" ]
    resources: [ "daemonsets" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "nodes", "pods" ]
    verbs: [ "get", "list", "watch" ]
