apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-metrics-server-testkube-job
  namespace: tks-system
---
apiVersion: v1
kind: Secret
metadata:
  name: test-metrics-server-testkube-job
  annotations:
    kubernetes.io/service-account.name: test-metrics-server-testkube-job
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
  name: test-metrics-server-clusterrolebinding-testkube-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-metrics-server-clusterrole-testkube-job
subjects:
  - kind: ServiceAccount
    name: test-metrics-server-testkube-job
    namespace: tks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
  name: test-metrics-server-clusterrole-testkube-job
rules:
  - apiGroups: [ "metrics.k8s.io" ]
    resources: [ "nodemetrics" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "metrics.k8s.io" ]
    resources: [ "nodemetrics" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "metrics.k8s.io" ]
    resources: [ "podmetrics" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "metrics.k8s.io" ]
    resources: [ "podmetrics" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "metrics.k8s.io" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "metrics.k8s.io" ]
    resources: [ "node" ]
    verbs: [ "get", "list", "watch" ]

