apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-vault-operator-testkube-job
  namespace: tks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
  name: test-vault-operator-clusterrolebinding-testkube-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-vault-operator-clusterrole-testkube-job
subjects:
  - kind: ServiceAccount
    name: test-vault-operator-testkube-job
    namespace: tks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
  name: test-vault-operator-clusterrole-testkube-job
rules:
  - apiGroups: [ "vault.banzaicloud.com" ]
    resources: [ "vaults" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts", "namespaces","pods" ]
    verbs: [ "*" ]
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles", "rolebindings" ]
    verbs: [ "*" ]
