apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-crossplane-testkube-job
  namespace: tks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: test-crossplane-clusterrolebinding-testkube-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-crossplane-clusterrole-testkube-job
subjects:
  - kind: ServiceAccount
    name: test-crossplane-testkube-job
    namespace: tks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: test-crossplane-clusterrole-testkube-job
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs: [ "get", "list", "watch" ]
  - apiGroups:
      - pkg.crossplane.io
    resources:
      - providers
    verbs: [ "*" ]
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs: [ "*" ]
  - apiGroups:
      - kubernetes.crossplane.io
    resources:
      - objectconfigs
    verbs: [ "*" ]
  - apiGroups:
      - ""
    resources:
      - namespaces
      - serviceaccounts
    verbs: [ "get","list","delete","create","watch","update" ]