apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
  name: test-integracao-tcloudwatch-testkube-job
  namespace: tks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
  name: test-integracao-tcloudwatch-clusterrolebinding-testkube-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-integracao-tcloudwatch-clusterrole-testkube-job
subjects:
  - kind: ServiceAccount
    name: test-integracao-tcloudwatch-testkube-job
    namespace: tks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
  name: test-integracao-tcloudwatch-clusterrole-testkube-job
rules:
 - apiGroups:
     - batch
   resources:
     - jobs
   verbs:
     - get
     - watch
     - list
     - create
     - delete
 - apiGroups:
     - ""
   resources:
     - pods
     - pods/log
   verbs:
     - get
     - watch
     - list
     - create
     - delete
 - apiGroups:
   - tests.testkube.io
   resources:
   - tests
   verbs:
   - create
   - delete
   - get
   - list
   - patch
   - update
   - watch
   - deletecollection
 - apiGroups:
   - tests.testkube.io
   resources:
   - tests/status
   verbs:
   - get
   - patch
   - update

