apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-argo-cd-testkube-job
  namespace: tks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: test-argo-cd-clusterrolebinding-testkube-job
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: test-argo-cd-clusterrole-testkube-job
subjects:
 - kind: ServiceAccount
   name: test-argo-cd-testkube-job
   namespace: tks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: test-argo-cd-clusterrole-testkube-job
rules:
 - apiGroups:
     - ""
   resources:
     - "*"
   verbs:
     - get
     - watch
     - list
     - create
     - delete