apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-istio-testkube-job
  namespace: tks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  argocd.argoproj.io/sync-wave: "-1"    
  name: test-istio-clusterrolebinding-testkube-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-istio-clusterrole-testkube-job
subjects:
  - kind: ServiceAccount
    name: test-ingress-nginx-testkube-job
    namespace: tks-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  argocd.argoproj.io/sync-wave: "-1"    
  name: test-istio-clusterrole-testkube-job
rules:
  - apiGroups: [ "install.istio.io" ]
    resources: [ "istiooperators" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch" ]
