apiVersion: tests.testkube.io/v1
kind: TestSource
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: testsource-tks-automated-tests
  namespace: tks-system
spec:
  type: git
  repository:
    type: git
    uri: https://github.com/cloud104/automated-tests.git
    branch: master
    path: /
