apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: test-istio
  namespace: testkube-system
  labels:
    executor: ginkgo-executor
    test-type: ginkgo-test
spec:
  type: ginkgo/test
  content:
    repository:
      branch: master
      path: executors/ginkgo/test-istio
  source: testsource-tks-automated-tests
  executionRequest:
    jobTemplateReference: job-template-worker-system
    executePostRunScriptBeforeScraping: false