apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-monitor-controller-testkube-job
  namespace: tks-system
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: ingress-monitor-controller-clusterrolebinding-testkube-job
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: ingress-monitor-controller-clusterrole-testkube-job
#subjects:
#  - kind: ServiceAccount
#    name: falco-testkube-job
#    namespace: tks-system
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: ingress-monitor-controller-clusterrole-testkube-job
#rules:
#  - apiGroups:
#      - batch
#    resources:
#      - jobs
#    verbs:
#      - get
#      - watch
#      - list
#      - create
#      - delete
#  - apiGroups:
#      - ""
#    resources:
#      - pods
#      - pods/log
#    verbs:
#      - get
#      - watch
#      - list
#      - create
#      - delete